apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventories
  labels:
    app: inventories
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventories
  template:
    metadata:
      labels:
        app: inventories
    spec:
      containers:
        - name: inventories
          image: username/inventories:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
